version: '1.0.0'

services:
  fastapi_service:
    build:
      context: ./  # Path to Dockerfile for app1
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        RUN_TYPE: app
    ports:
      - "8080:8080"          # Map ports as needed
    depends_on:
      - mysql
      - kafka

  consumer:
    build:
      context: ./
      dockerfile: consumer_Dockerfile  # Path to Dockerfile for app2
      args:
        ENVIRONMENT: dev
        RUN_TYPE: app
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /tmp/data:/var/lib/mysql

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
